import { StyleSheet } from "react-native";
import palette from "./theme";

const globalStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.paper,
    position: "relative",
  },
  keyboardView: {
    flex: 1,
    marginTop: 60,
  },
  scrollContent: {
    padding: 0,
    paddingBottom: 32,
    gap: 0,
    alignItems: "stretch",
  },
  appHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    zIndex: 10000,
    backgroundColor: "#ffffff",
  },
  menuButton: {
    width: 36,
    height: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  menuIcon: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 20,
  },
  screenTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  headerSpacer: {
    width: 36,
    height: 36,
  },
  menuPanel: {
    position: "absolute",
    top: 60,
    left: 16,
    width: 132,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 12,
    padding: 6,
    backgroundColor: "#ffffff",
    shadowColor: "#151515",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 1000,
    zIndex: 99999,
  },
  menuItem: {
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  menuItemActive: {
    backgroundColor: "#f2f2f2",
  },
  menuItemText: {
    color: palette.muted,
    fontSize: 15,
    fontWeight: "800",
  },
  menuItemTextActive: {
    color: palette.ink,
  },
  panel: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  topRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  segment: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    padding: 4,
    backgroundColor: "#ffffff",
  },
  segmentItem: {
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 16,
  },
  segmentItemActive: {
    backgroundColor: palette.ink,
  },
  segmentText: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#f8fff5",
  },
  segmentCompact: {
    padding: 2,
  },
  segmentItemCompact: {
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  segmentTextCompact: {
    fontSize: 12,
    fontWeight: "700",
  },
  clearButton: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  clearText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldGrid: {
    gap: 10,
    marginTop: 14,
  },
  field: {
    gap: 7,
  },
  fieldLabel: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "700",
  },
  fieldLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 7,
    paddingHorizontal: 14,
    color: palette.ink,
    backgroundColor: "#ffffff",
    fontSize: 17,
  },
  stepInputRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "stretch",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 7,
    overflow: "hidden",
    backgroundColor: "#ffffff",
  },
  stepInput: {
    flex: 1,
    paddingHorizontal: 14,
    color: palette.ink,
    fontSize: 17,
  },
  stepButton: {
    width: 46,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "#eeeeee",
    backgroundColor: "#fafafa",
  },
  stepButtonText: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "900",
  },
  quickRates: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickRate: {
    flexGrow: 1,
    flexBasis: "18%",
    minWidth: 56,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "transparent",
  },
  quickRateActive: {
    backgroundColor: palette.ink,
    borderColor: palette.ink,
  },
  quickRateText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  quickRateTextActive: {
    color: "#ffffff",
  },
  hoverTipWrap: {
    position: "relative",
    zIndex: 2,
  },
  hoverTipTrigger: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.muted,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  hoverTipTriggerText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 12,
  },
  hoverTipBubble: {
    position: "absolute",
    left: 22,
    top: -6,
    minWidth: 200,
    maxWidth: 260,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#e2e2e2",
    borderRadius: 7,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: "#f7f7f7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  hoverTipText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  feeRow: {
    flexDirection: "column",
    gap: 8,
    marginTop: 14,
  },
  feeChip: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#e2e2e2",
    borderRadius: 7,
    paddingVertical: 7,
    paddingHorizontal: 10,
    color: palette.ink,
    backgroundColor: "#f7f7f7",
    fontSize: 13,
    fontWeight: "700",
    width: "100%",
  },
  resultPanel: {
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  primaryResult: {
    borderRadius: 8,
    padding: 18,
    backgroundColor: palette.ink,
  },
  primaryGain: {
    backgroundColor: palette.profitRed,
  },
  primaryLoss: {
    backgroundColor: palette.lossGreen,
  },
  primaryLabel: {
    color: "rgba(248, 255, 245, 0.78)",
    fontWeight: "700",
    marginBottom: 8,
  },
  primaryValue: {
    color: "#f8fff5",
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
  },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  metric: {
    width: "48%",
    minWidth: 145,
    borderWidth: 1,
    borderColor: "#eeeeee",
    borderRadius: 7,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  metricLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 7,
  },
  metricValue: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "800",
  },
  contractGainMetric: {
    borderColor: "rgba(15, 123, 85, 0.38)",
    backgroundColor: "rgba(15, 123, 85, 0.08)",
  },
  contractLossMetric: {
    borderColor: "rgba(182, 48, 48, 0.34)",
    backgroundColor: "rgba(182, 48, 48, 0.08)",
  },
  contractGainText: {
    color: palette.lossGreen,
  },
  contractLossText: {
    color: palette.profitRed,
  },
  formula: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 7,
    padding: 12,
    color: palette.muted,
    backgroundColor: "#ffffff",
    lineHeight: 22,
  },
  confirmButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    marginTop: 12,
    backgroundColor: palette.ink,
  },
  disabledButton: {
    opacity: 0.35,
  },
  confirmText: {
    color: "#f8fff5",
    fontSize: 16,
    fontWeight: "900",
  },
  gapCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 8,
    padding: 18,
    backgroundColor: "#ffffff",
  },
  gapCardTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  gapCardPrice: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 2,
  },
  gapCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 4,
  },
  gapCardTitleInline: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    flexShrink: 0,
  },
  gapBlock: {
    gap: 6,
  },
  gapRowSpaced: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0.06)",
  },
  gapLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  gapMetrics: {
    flexDirection: "row",
    gap: 16,
  },
  gapMetricItem: {
    flex: 1,
    minWidth: 0,
  },
  gapMetricLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  gapMetricValue: {
    color: palette.ink,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
  },
  gapUpText: {
    color: palette.lossGreen,
  },
  gapDownText: {
    color: palette.profitRed,
  },
  gapEmpty: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 8,
  },
  roiCardRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
  },
  roiCard: {
    flex: 1,
    minWidth: 0,
  },
  roiCardLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  roiCardValue: {
    color: palette.ink,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
  },
  roiCardSubValue: {
    color: palette.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    marginTop: 2,
  },
  reachStack: {
    marginTop: 10,
  },
  reachStackItem: {
    gap: 4,
  },
  reachStackItemSpaced: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0.06)",
  },
  metricKvList: {
    marginTop: 6,
    gap: 8,
  },
  metricKvRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  metricKvKey: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 0,
  },
  metricKvValue: {
    color: palette.ink,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "right",
    flex: 1,
  },
  metricKvValuePlain: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400",
    textAlign: "right",
    flex: 1,
  },
  triggerCard: {
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    backgroundColor: "#ffffff",
  },
  triggerCardGain: {
    borderColor: "rgba(15, 123, 85, 0.45)",
    backgroundColor: "#ffffff",
  },
  triggerCardLoss: {
    borderColor: "rgba(211, 47, 47, 0.45)",
    backgroundColor: "#ffffff",
  },
  triggerCardSpaced: {
    marginTop: 14,
  },
  triggerCardLabel: {
    color: palette.muted,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 13,
  },
  triggerCardValue: {
    color: palette.ink,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
  },
  triggerKvList: {
    marginTop: 14,
    gap: 10,
  },
  triggerMetricRow: {
    marginTop: 0,
  },
  riskRewardDivider: {
    marginVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  riskRewardLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#e6e6e6",
  },
  riskRewardBadge: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    backgroundColor: "#f7f7f7",
  },
  riskRewardBadgeLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  riskRewardBadgeValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  leverageBadge: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "#f7f7f7",
  },
  leverageBadgeText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
  },
});

export default globalStyles;
