import { StyleSheet } from "react-native";
import palette from "../../styles/theme";

const styles = StyleSheet.create({
  page: { width: "100%", padding: 12, gap: 12 },
  pageDesktop: { maxWidth: 760 },
  metrics: { flexDirection: "row", paddingVertical: 4 },
  metric: { flex: 1, minWidth: 0, paddingVertical: 10, paddingHorizontal: 12 },
  metricDivider: { borderLeftWidth: 1, borderLeftColor: palette.line },
  metricValue: { color: palette.ink, fontSize: 21, fontWeight: "900" },
  metricLabel: { color: palette.muted, fontSize: 11, fontWeight: "700", marginTop: 3 },
  presentText: { color: "#2563eb" },
  absentText: { color: palette.profitRed },
  rateText: { color: "#27966f" },
  calendar: { paddingVertical: 14, backgroundColor: palette.paper },
  calendarHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  navButton: { width: 38, height: 38, borderWidth: 1, borderColor: palette.line, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  navText: { color: palette.ink, fontSize: 27, lineHeight: 29, fontWeight: "500" },
  monthTitle: { color: palette.ink, fontSize: 18, fontWeight: "900", letterSpacing: 1 },
  weekRow: { flexDirection: "row", marginBottom: 5 },
  weekday: { width: "14.2857%", textAlign: "center", color: palette.muted, fontSize: 11, fontWeight: "800" },
  weekend: { color: "#ae8279" },
  daysGrid: { flexDirection: "row", flexWrap: "wrap" },
  dayCell: { width: "14.2857%", aspectRatio: 1, alignItems: "center", justifyContent: "center", position: "relative" },
  dayNumber: { color: palette.ink, fontSize: 14, fontWeight: "700" },
  weekendCell: { opacity: 0.42 },
  weekendNumber: { color: palette.muted },
  outsideMonthCell: { opacity: 0.58 },
  outsideMonthNumber: { color: palette.muted },
  todayCell: { borderWidth: 1, borderColor: palette.ink },
  presentCell: { backgroundColor: "#e8f0ff" },
  absentCell: { backgroundColor: "#fdebea" },
  presentNumber: { color: "#2563eb" },
  absentNumber: { color: palette.profitRed },
  statusDot: { position: "absolute", bottom: 5, width: 4, height: 4, borderRadius: 2 },
  dayBadge: { position: "absolute", top: 4, right: 5, width: 16, height: 16, borderRadius: 8, textAlign: "center", fontSize: 9, lineHeight: 16, fontWeight: "900", overflow: "hidden" },
  holidayBadge: { color: "#b42318", backgroundColor: "#fee4e2" },
  workBadge: { color: "#175cd3", backgroundColor: "#dbeafe" },
  presentDot: { backgroundColor: "#2563eb" },
  absentDot: { backgroundColor: palette.profitRed },
  legend: { marginTop: 14, paddingTop: 14, paddingHorizontal: 10, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 13 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 7, height: 7, borderRadius: 4 },
  legendText: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  legendBadge: { width: 16, height: 16, borderRadius: 8, textAlign: "center", fontSize: 9, lineHeight: 16, fontWeight: "900", overflow: "hidden" },
  formula: { color: palette.muted, fontSize: 10, marginLeft: "auto" },
  todayButtonRow: { marginTop: 12, paddingHorizontal: 10, alignItems: "flex-start" },
  todayButton: { paddingVertical: 7, paddingHorizontal: 16, borderWidth: 1, borderColor: palette.line, borderRadius: 999, alignItems: "center", backgroundColor: palette.paper },
  todayButtonPressed: { backgroundColor: "#f4f4f4" },
  todayButtonText: { color: palette.muted, fontSize: 11, fontWeight: "700" },
});

export default styles;
