import { StyleSheet } from "react-native";
import palette from "../../styles/theme";

const styles = StyleSheet.create({
  page: { width: "100%", padding: 12, gap: 12 },
  pageDesktop: { maxWidth: 760 },
  hero: { minHeight: 108, paddingVertical: 16, paddingHorizontal: 20, borderRadius: 8, backgroundColor: palette.ink, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  heroTitle: { color: palette.paper, fontSize: 26, lineHeight: 32, fontWeight: "900" },
  heroHint: { color: "#a9a9a9", fontSize: 12, marginTop: 6 },
  rateBlock: { alignItems: "flex-end" },
  rateValue: { color: "#a8e6ca", fontSize: 38, lineHeight: 42, fontWeight: "900" },
  rateLabel: { color: "#a9a9a9", fontSize: 11, fontWeight: "700", marginTop: 2 },
  metrics: { flexDirection: "row", gap: 8 },
  metric: { flex: 1, minWidth: 0, paddingVertical: 12, paddingHorizontal: 10, borderWidth: 1, borderColor: palette.line, borderRadius: 8, backgroundColor: palette.paper },
  metricValue: { color: palette.ink, fontSize: 21, fontWeight: "900" },
  metricLabel: { color: palette.muted, fontSize: 11, fontWeight: "700", marginTop: 3 },
  presentText: { color: palette.lossGreen },
  leaveText: { color: "#a36b00" },
  absentText: { color: palette.profitRed },
  calendar: { padding: 14, borderWidth: 1, borderColor: palette.line, borderRadius: 8, backgroundColor: palette.paper },
  calendarHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  navButton: { width: 38, height: 38, borderWidth: 1, borderColor: palette.line, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  navText: { color: palette.ink, fontSize: 27, lineHeight: 29, fontWeight: "500" },
  monthTitle: { color: palette.ink, fontSize: 18, fontWeight: "900", letterSpacing: 1 },
  weekRow: { flexDirection: "row", marginBottom: 5 },
  weekday: { width: "14.2857%", textAlign: "center", color: palette.muted, fontSize: 11, fontWeight: "800" },
  weekend: { color: "#ae8279" },
  daysGrid: { flexDirection: "row", flexWrap: "wrap" },
  dayCell: { width: "14.2857%", aspectRatio: 1, alignItems: "center", justifyContent: "center", borderRadius: 8, position: "relative" },
  dayNumber: { color: palette.ink, fontSize: 14, fontWeight: "700" },
  weekendCell: { opacity: 0.42 },
  weekendNumber: { color: palette.muted, textDecorationLine: "line-through" },
  outsideMonthCell: { opacity: 0.3 },
  outsideMonthNumber: { color: palette.muted },
  todayCell: { borderWidth: 1, borderColor: palette.ink },
  presentCell: { backgroundColor: "#e8f7f0" },
  leaveCell: { backgroundColor: "#fff4d6" },
  absentCell: { backgroundColor: "#fdebea" },
  presentNumber: { color: palette.lossGreen },
  leaveNumber: { color: "#8a5a00" },
  absentNumber: { color: palette.profitRed },
  statusDot: { position: "absolute", bottom: 5, width: 4, height: 4, borderRadius: 2 },
  presentDot: { backgroundColor: palette.lossGreen },
  leaveDot: { backgroundColor: "#c88700" },
  absentDot: { backgroundColor: palette.profitRed },
  legend: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 13 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 7, height: 7, borderRadius: 4 },
  legendText: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  formula: { color: palette.muted, fontSize: 10, marginLeft: "auto" },
});

export default styles;
