import { StyleSheet } from "react-native";
import palette from "../../styles/theme";

const styles = StyleSheet.create({
  panel: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  topRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  leverageBadge: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "#f7f7f7",
  },
  leverageBadgeText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  clearButton: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  clearText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldGrid: {
    gap: 10,
    marginTop: 14,
  },
  positionCard: {
    borderWidth: 1,
    borderColor: "#e2e2e2",
    borderRadius: 10,
    padding: 12,
    gap: 10,
    backgroundColor: "#fafafa",
  },
  positionCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  positionCardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: palette.ink,
  },
  positionCardHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  positionTotalLot: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.muted,
  },
  addPositionButton: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: palette.ink,
    borderRadius: 6,
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: "#ffffff",
  },
  addPositionText: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.ink,
  },
  positionItem: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 8,
    padding: 10,
    gap: 8,
    backgroundColor: "#ffffff",
  },
  positionItemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  positionItemLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: palette.muted,
  },
  removePositionButton: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    backgroundColor: "#fdecea",
    borderRadius: 5,
  },
  removePositionText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#d32f2f",
  },
  avgCostRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#e2e2e2",
    paddingTop: 8,
  },
  avgCostLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: palette.muted,
  },
  avgCostValue: {
    fontSize: 17,
    fontWeight: "900",
    color: palette.ink,
  },
  quickRates: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickRate: {
    flexGrow: 1,
    flexBasis: "18%",
    minWidth: 56,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "transparent",
  },
  quickRateActive: {
    backgroundColor: palette.ink,
    borderColor: palette.ink,
  },
  quickRateText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  quickRateTextActive: {
    color: "#ffffff",
  },
  feeRow: {
    flexDirection: "column",
    gap: 8,
    marginTop: 14,
  },
  feeChip: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#e2e2e2",
    borderRadius: 7,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#f7f7f7",
    width: "100%",
    gap: 4,
  },
  feeChipTitle: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  feeChipBody: {
    color: palette.ink,
    fontSize: 12.5,
    fontWeight: "700",
    lineHeight: 18,
    opacity: 0.92,
  },
  feeChipDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#dcdcdc",
  },
  feeChipHint: {
    color: "#8a8a8a",
    fontSize: 11.5,
    fontWeight: "500",
    lineHeight: 16,
  },
  feeChipEmph: {
    fontWeight: "900",
    color: palette.ink,
  },
  feeChipResultHighlight: {
    color: "#d32f2f",
    fontWeight: "900",
  },
  resultPanel: {
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  triggerCard: {
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e8e8e8",
    backgroundColor: "#ffffff",
  },
  triggerCardSpaced: {
    marginTop: 14,
  },
  triggerReachedHint: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#e8e8e8",
  },
  triggerReachedText: {
    color: "#d32f2f",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "left",
  },
  triggerCardLoss: {
    borderColor: "rgba(211, 47, 47, 0.45)",
    backgroundColor: "#ffffff",
  },
  triggerCardLabel: {
    color: palette.muted,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 13,
  },
  triggerCardValue: {
    color: palette.ink,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
  },
  marginCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  marginCardHelpIcon: {
    fontSize: 16,
    color: palette.muted,
    fontWeight: "700",
  },
  marginLevelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  riskBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: "#ffffff",
  },
  riskBadgeText: {
    fontSize: 13,
    fontWeight: "800",
  },
  riskDesc: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
  },
  triggerKvList: {
    marginTop: 14,
    gap: 10,
  },
  triggerMetricRow: {
    marginTop: 0,
  },
  roiCardRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
  },
  roiCard: {
    flex: 1,
    minWidth: 0,
  },
  roiCardGain: {},
  roiCardLoss: {},
  roiCardLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  roiCardValue: {
    color: palette.ink,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
  },
  gapUpText: {
    color: palette.lossGreen,
  },
  gapDownText: {
    color: palette.profitRed,
  },
  gapCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 8,
    padding: 18,
    backgroundColor: "#ffffff",
  },
  gapCardTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  gapCardPrice: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 2,
  },
  reachStack: {
    marginTop: 10,
  },
  reachStackItem: {
    gap: 4,
  },
  metricKvList: {
    marginTop: 6,
    gap: 8,
  },
  metricKvRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  metricKvKey: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 0,
  },
  metricKvValue: {
    color: palette.ink,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "right",
    flex: 1,
  },
  metricKvValuePlain: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400",
    textAlign: "right",
    flex: 1,
  },
  gapEmpty: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 8,
  },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  confirmButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    marginTop: 12,
    backgroundColor: palette.ink,
  },
  disabledButton: {
    opacity: 0.35,
  },
  confirmText: {
    color: "#f8fff5",
    fontSize: 16,
    fontWeight: "900",
  },
  marginHelpOverlay: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  marginHelpBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  marginHelpSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 18,
    zIndex: 1,
    maxHeight: "85%",
  },
  marginHelpHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  marginHelpTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  marginHelpCloseBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: "#f0f0f0",
    borderRadius: 6,
  },
  marginHelpCloseText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  marginHelpSection: {
    marginBottom: 16,
  },
  marginHelpSectionTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 10,
  },
  marginHelpFormulaBox: {
    backgroundColor: "#f7f7f7",
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 6,
  },
  marginHelpFormula: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: "monospace",
  },
  marginHelpRiskRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  marginHelpRiskDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 5,
  },
  marginHelpRiskContent: {
    flex: 1,
  },
  marginHelpRiskLevel: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 3,
  },
  marginHelpRiskDesc: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
});

export default styles;
