import { StyleSheet } from "react-native";
import palette from "../../styles/theme";

const styles = StyleSheet.create({
  panel: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  clearButton: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  clearText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldGrid: {
    gap: 10,
    marginTop: 14,
  },
  hoverTipWrap: {
    position: "relative",
    zIndex: 2,
  },
  hoverTipTrigger: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.muted,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  hoverTipTriggerText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 12,
  },
  hoverTipBubble: {
    position: "absolute",
    left: 22,
    top: -6,
    minWidth: 200,
    maxWidth: 260,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#e2e2e2",
    borderRadius: 7,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: "#f7f7f7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  hoverTipText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  quickRates: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickRate: {
    flexGrow: 1,
    flexBasis: "18%",
    minWidth: 56,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "transparent",
  },
  quickRateActive: {
    backgroundColor: palette.ink,
    borderColor: palette.ink,
  },
  quickRateText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  quickRateTextActive: {
    color: "#ffffff",
  },
  gapCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 8,
    padding: 18,
    backgroundColor: "#ffffff",
  },
  gapCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 4,
  },
  gapCardTitleInline: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    flexShrink: 0,
  },
  gapCardTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 4,
  },
  gapCardPrice: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 2,
  },
  gapUpText: {
    color: palette.lossGreen,
  },
  gapDownText: {
    color: palette.profitRed,
  },
  gapEmpty: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 8,
  },
  reachStack: {
    marginTop: 10,
  },
  reachStackItem: {
    gap: 4,
  },
  reachStackItemSpaced: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0.06)",
  },
  roiCardLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  metricKvList: {
    marginTop: 6,
    gap: 8,
  },
  metricKvRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  metricKvKey: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    flexShrink: 0,
  },
  metricKvValue: {
    color: palette.ink,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "right",
    flex: 1,
  },
  metricKvValuePlain: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400",
    textAlign: "right",
    flex: 1,
  },
  roiCardRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
  },
  roiCard: {
    flex: 1,
    minWidth: 0,
  },
  roiCardGain: {},
  roiCardLoss: {},
  roiCardValue: {
    color: palette.ink,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "900",
  },
  resultPanel: {
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  triggerCard: {
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    backgroundColor: "#ffffff",
  },
  triggerCardSpaced: {
    marginTop: 14,
  },
  triggerCardGain: {
    borderColor: "rgba(15, 123, 85, 0.45)",
    backgroundColor: "#ffffff",
  },
  triggerCardLoss: {
    borderColor: "rgba(211, 47, 47, 0.45)",
    backgroundColor: "#ffffff",
  },
  triggerCardLabel: {
    color: palette.muted,
    fontWeight: "700",
    marginBottom: 8,
    fontSize: 13,
  },
  triggerCardValue: {
    color: palette.ink,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "900",
  },
  triggerKvList: {
    marginTop: 14,
    gap: 10,
  },
  triggerMetricRow: {
    marginTop: 0,
  },
  riskRewardDivider: {
    marginVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  riskRewardLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#e6e6e6",
  },
  riskRewardBadge: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    backgroundColor: "#f7f7f7",
  },
  riskRewardBadgeLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  riskRewardBadgeValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  confirmButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    marginTop: 12,
    backgroundColor: palette.ink,
  },
  disabledButton: {
    opacity: 0.35,
  },
  confirmText: {
    color: "#f8fff5",
    fontSize: 16,
    fontWeight: "900",
  },
});

export default styles;
