import { StyleSheet } from "react-native";

const palette = {
  ink: "#151515",
  muted: "#6d6d6d",
  paper: "#ffffff",
  panel: "#ffffff",
  line: "#e4e4e4",
  accent: "#151515",
  accentStrong: "#151515",
  profitRed: "#d32f2f",
  lossGreen: "#0f7b55",
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.paper,
    position: "relative",
  },
  keyboardView: {
    flex: 1,
    marginTop: 60,
  },
  scrollContent: {
    padding: 0,
    paddingBottom: 32,
    gap: 0,
    alignItems: "stretch",
  },
  mainContainer: {
    flexDirection: "column",
    gap: 16,
    paddingHorizontal: 12,
    paddingTop: 16,
  },
  panelColumn: {
    width: "100%",
  },
  panelContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  appHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    zIndex: 10000,
    backgroundColor: "#ffffff",
  },
  menuButton: {
    width: 36,
    height: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  menuIcon: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 20,
  },
  screenTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  headerSpacer: {
    width: 36,
    height: 36,
  },
  menuPanel: {
    position: "absolute",
    top: 60,
    left: 16,
    width: 132,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 12,
    padding: 6,
    backgroundColor: "#ffffff",
    shadowColor: "#151515",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 1000,
    zIndex: 99999,
  },
  menuItem: {
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  menuItemActive: {
    backgroundColor: "#f2f2f2",
  },
  menuItemText: {
    color: palette.muted,
    fontSize: 15,
    fontWeight: "800",
  },
  menuItemTextActive: {
    color: palette.ink,
  },
  panel: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  segment: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    padding: 4,
    backgroundColor: "#ffffff",
  },
  segmentItem: {
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 16,
  },
  segmentItemActive: {
    backgroundColor: palette.ink,
  },
  segmentText: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: "#f8fff5",
  },
  clearButton: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  clearText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  fieldGrid: {
    gap: 10,
    marginTop: 14,
  },
  field: {
    gap: 7,
  },
  fieldLabel: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "700",
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 7,
    paddingHorizontal: 14,
    color: palette.ink,
    backgroundColor: "#ffffff",
    fontSize: 17,
  },
  stepInputRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "stretch",
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 7,
    overflow: "hidden",
    backgroundColor: "#ffffff",
  },
  stepInput: {
    flex: 1,
    paddingHorizontal: 14,
    color: palette.ink,
    fontSize: 17,
  },
  stepButton: {
    width: 46,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "#eeeeee",
    backgroundColor: "#fafafa",
  },
  stepButtonText: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "900",
  },
  quickRates: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickRate: {
    flexGrow: 1,
    flexBasis: "18%",
    minWidth: 56,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "transparent",
  },
  quickRateActive: {
    backgroundColor: palette.ink,
    borderColor: palette.ink,
  },
  quickRateText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  quickRateTextActive: {
    color: "#ffffff",
  },
  gapCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#eeeeee",
    borderRadius: 8,
    padding: 14,
    backgroundColor: "#fafafa",
  },
  gapCardTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 10,
  },
  gapRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  gapRowSpaced: {
    marginTop: 12,
  },
  gapLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  gapValue: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
    flexShrink: 1,
    textAlign: "right",
  },
  gapSub: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "right",
  },
  gapEmpty: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
  },
  feeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  feeChip: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#e2e2e2",
    borderRadius: 7,
    paddingVertical: 7,
    paddingHorizontal: 10,
    color: palette.ink,
    backgroundColor: "#f7f7f7",
    fontSize: 13,
    fontWeight: "700",
  },
  resultPanel: {
    borderWidth: 0,
    borderRadius: 7,
    backgroundColor: "transparent",
    padding: 12,
    elevation: 0,
  },
  primaryResult: {
    borderRadius: 8,
    padding: 18,
    backgroundColor: palette.ink,
  },
  primaryGain: {
    backgroundColor: palette.profitRed,
  },
  primaryLoss: {
    backgroundColor: palette.lossGreen,
  },
  primaryLabel: {
    color: "rgba(248, 255, 245, 0.78)",
    fontWeight: "700",
    marginBottom: 8,
  },
  primaryValue: {
    color: "#f8fff5",
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "900",
  },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  metric: {
    width: "48%",
    minWidth: 145,
    borderWidth: 1,
    borderColor: "#eeeeee",
    borderRadius: 7,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  metricLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 7,
  },
  metricValue: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "800",
  },
  contractGainMetric: {
    borderColor: "rgba(15, 123, 85, 0.38)",
    backgroundColor: "rgba(15, 123, 85, 0.08)",
  },
  contractLossMetric: {
    borderColor: "rgba(182, 48, 48, 0.34)",
    backgroundColor: "rgba(182, 48, 48, 0.08)",
  },
  contractGainText: {
    color: palette.lossGreen,
  },
  contractLossText: {
    color: palette.profitRed,
  },
  formula: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 7,
    padding: 12,
    color: palette.muted,
    backgroundColor: "#ffffff",
    lineHeight: 22,
  },
  confirmButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    marginTop: 12,
    backgroundColor: palette.ink,
  },
  disabledButton: {
    opacity: 0.35,
  },
  confirmText: {
    color: "#f8fff5",
    fontSize: 16,
    fontWeight: "900",
  },
  historyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 40,
  },
  historyItem: {
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e6e6e6",
    marginBottom: 10,
  },
  historyProfitItem: {
    borderColor: palette.profitRed,
  },
  historyItemTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  historyType: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  historyTime: {
    color: palette.muted,
    fontSize: 12,
  },
  historyDetail: {
    gap: 6,
  },
  historyDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  historyDetailLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  historyDetailValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "600",
  },
  historySummaryValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  klineSectionLabel: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  klinePeriodRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  klinePeriodChip: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: "#ffffff",
  },
  klinePeriodChipActive: {
    backgroundColor: palette.ink,
    borderColor: palette.ink,
  },
  klinePeriodChipText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  klinePeriodChipTextActive: {
    color: "#f8fff5",
  },
  klineDateTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  klineDateField: {
    position: "relative",
    zIndex: 5,
    overflow: "visible",
  },
  klineHint: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  klineDateFallback: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fafafa",
  },
  klineDateFallbackText: {
    color: palette.muted,
    fontSize: 13,
  },
  klineResultValue: {
    color: "#f8fff5",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  klineResultBox: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 7,
    padding: 12,
    backgroundColor: "#ffffff",
  },
  klineResultText: {
    color: palette.ink,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "600",
  },
  sessionContainer: {
    paddingBottom: 16,
  },
  sessionNowBar: {
    borderBottomWidth: 1,
    borderBottomColor: "#ececec",
    paddingVertical: 18,
    paddingHorizontal: 2,
    marginBottom: 18,
    alignItems: "center",
  },
  sessionNowLabel: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  sessionNowValue: {
    color: palette.ink,
    fontSize: 28,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
    letterSpacing: 0.4,
    textAlign: "center",
  },
  sessionGrid: {
    gap: 16,
  },
  sessionGridDesktop: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  sessionCard: {
    borderWidth: 1,
    borderColor: "#e6e6e6",
    borderRadius: 8,
    padding: 16,
    backgroundColor: "#ffffff",
  },
  sessionCardDesktop: {
    width: "48%",
    minWidth: 280,
  },
  sessionCardActive: {
    borderColor: palette.ink,
  },
  sessionCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
    gap: 8,
  },
  sessionCardTopRight: {
    alignItems: "flex-end",
    gap: 6,
  },
  sessionName: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  sessionIndexNote: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  sessionIndexLink: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
    textDecorationLine: "none",
  },
  sessionStatusText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  sessionStatusTextActive: {
    color: palette.ink,
  },
  phaseList: {
    marginTop: 8,
  },
  phaseRow: {
    position: "relative",
    overflow: "hidden",
  },
  phaseRowDivided: {
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  phaseRowActive: {
    backgroundColor: "#f7f7f7",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  phaseProgressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(21, 21, 21, 0.07)",
  },
  phaseRowInner: {
    position: "relative",
    zIndex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 11,
  },
  phaseLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "left",
  },
  phaseLabelActive: {
    color: palette.ink,
  },
  phaseMain: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
  },
  phaseTime: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
    textAlign: "right",
    flexShrink: 0,
  },
  phaseTimeActive: {
    color: palette.ink,
  },
  phaseHint: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
    textAlign: "left",
  },
  sessionCardFooter: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  sessionCountdownEntry: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: "#ffffff",
  },
  sessionCountdownEntryText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  countdownOverlay: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  countdownBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  countdownSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    maxHeight: "80%",
    zIndex: 1,
  },
  countdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
  },
  countdownTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: "900",
    flex: 1,
  },
  countdownCloseBtn: {
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  countdownCloseText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  countdownSub: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 8,
  },
  countdownList: {
    paddingBottom: 6,
  },
  countdownRow: {
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  countdownRowDivided: {
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  countdownRowCurrent: {
    backgroundColor: "#f7f7f7",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  countdownRowLeft: {
    flex: 1,
    minWidth: 0,
  },
  countdownPhaseLabel: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  countdownPhaseRange: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
    fontVariant: ["tabular-nums"],
  },
  countdownRowRight: {
    alignItems: "flex-end",
  },
  countdownCaption: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  countdownValue: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "900",
    marginTop: 2,
    fontVariant: ["tabular-nums"],
  },
  countdownValueCurrent: {
    color: palette.profitRed,
  },
  sessionDstText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "600",
  },
  sessionFooter: {
    marginTop: 14,
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
  },
});

export { palette };
export default styles;