server {
    listen 80;
    server_name _;

    location = / {
        return 302 /t-calculator/;
    }

    location /t-calculator {
        return 302 /t-calculator/;
    }

    location /t-calculator/ {
        alias /usr/share/nginx/html/t-calculator/;
        index index.html;
        try_files $uri $uri/ index.html;
    }
}